kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: pre-build
    commands:
      - docker container stop faktura.exe || true
      - docker rmi faktura:latest || true
      - echo 'Complete pre-build'
  - name: build
    commands:
      - docker build -t faktura:latest .
      - echo 'Build complete'
  - name: deploy
    commands:
      - docker run -d --rm --name faktura.exe -p 8080:8080 faktura:latest
      - echo 'Deploy complete'

trigger:
  branch:
    - release
  event:
    - push