kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: pre-build
    commands:
      - docker container faktura.exe stop
      - docker rmi faktura:latest
  - name: build
    commands:
      - docker build -t faktura:latest .
  - name: deploy
    commands:
      - docker run -d --rm --name faktura.exe -p 8080:8080 faktura:latest